### ISSUE TITLE
Please make badge optional

### ISSUE THREAD

**Issue by mariusa** [ReeceM/h-bar#29]
https://github.com/ReeceM/h-bar/blob/a5c91e33d6589215af48388467840dc5edaac79c/src/functions/init.js#L34

Now one cannot hide the badge unless setting it to a space. 
It would be better to have no default value (set it to `New` only in examples), and let users set it, if they want.

**Comment by ReeceM** [comment]
Hi @mariusa 

Thank you for that, I'm happy for you to make a PR for that change if you have the time, I may only get to that later in the week at the moment.

Otherwise, that is a good suggestion, thank you 💯

**Comment by mariusa** [comment]
Done :)

**Comment by ReeceM** [comment]
Thank you, PR merged 💯
