### ISSUE TITLE
Have a tiny padding on the right too (remove  hb--mr-2 ?)

### ISSUE THREAD

**Issue by mariusa** [ReeceM/h-bar#30]
Hi,

https://github.com/ReeceM/h-bar/blob/a5c91e33d6589215af48388467840dc5edaac79c/src/banner/banner.js#L97

By default, the bar looks like this on a small screen:
![Screenshot from 2022-12-21 11-49-29](https://user-images.githubusercontent.com/1283842/208875297-041310b8-a4c3-45c7-8ae5-910da3376f9f.png)

When disabling `hb--mr-2`, it fixes the display to have a tiny padding on the right too 
```
.hb--mr-2 {
    /* margin-right: -0.5rem; */
}
```
![Screenshot from 2022-12-21 11-49-34](https://user-images.githubusercontent.com/1283842/208875444-551b9942-5f2e-462d-ab08-a8cbe50c2a90.png)

Maybe that class shouldn't be added?

**Comment by ReeceM** [comment]
Tracked in PR #37 This is a bug on smaller screens.

**Comment by mariusa** [comment]
Thank you :D
