### ISSUE TITLE
customStyles ignored in 2.0

### ISSUE THREAD

**Issue by mariusa** [ReeceM/h-bar#34]
`customStyles` seems ignored in 2.0 ?
https://cdn.jsdelivr.net/npm/@reecem/h-bar@next/dist/hBar.js

Looks like this was lost:
` this.styling = Object.assign(styling, options.customStyles);`

Also, I think custom styles should be added after theme styles, so they take priority and overwrite theme:
`classes: "".concat(_this2.styling.wrapper, " ").concat(themes[_this2.theme].wrapper),`

**Comment by ReeceM** [comment]
Thank you, this is very likely to the fact I had the intention to remove it but then stopped halfway. It was originally from v1 that those were added, it overrides the default styling.

But I think I will keep that option there as some possibly use it still

**Comment by mariusa** [comment]
Thanks :) I'd like to slightly adjust the defaults, which is/should be good enough for me not to require a completely different template (and that DOM* dependency)

**Comment by ReeceM** [comment]
You can run the template without the DOMPurify requirement by default, I actually forgot that fact.

---

Another option if you want to bypass the renderer completely and use your own template I forgot that I added a way to override the internal template rendering.

If you don't define the template on `data-template` and then provide your own render object you can just return html. Do this if you trust the source. But it should help you for now :)
